### ISSUE TITLE
perf: investigate using jemalloc

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#1372]
We do a lot of `take` and `compact_batches`, which involves moving data to new buffers. It might be worth seeing if a memory pool like jemalloc would help here.

The tool https://github.com/koute/bytehound might come in handy.

**Comment by wjones127** [comment]
Just did some quick performance tests, and it seems like overall jemalloc would be an improvement in our current benchmark suite.

<details><summary>Changes for benchmark</summary>
<p>

In `Cargo.toml`:

```toml
# Allocators
mimalloc = { version = "0.1.39", optional = true }
jemallocator = { version = "0.5.4", optional = true, features = ["disable_initial_exec_tls"] }
snmalloc-rs = { version = "0.3.4", optional = true, features = ["local_dynamic_tls"] }
```

In `python/src/lib.rs`:

```rust
// Set global allocator
#[cfg(feature = "mimalloc")]
#[global_allocator]
static GLOBAL: mimalloc::MiMalloc = mimalloc::MiMalloc;
#[cfg(feature = "snmalloc-rs")]
#[global_allocator]
static GLOBAL: snmalloc_rs::SnMalloc = snmalloc_rs::SnMalloc;
#[cfg(feature = "jemallocator")]
#[global_allocator]
static GLOBAL: jemallocator::Jemalloc = jemallocator::Jemalloc;
```

</p>
</details> 

On MacOS, I find jemalloc is good in almost all situations, except for some regressions in writes:

![Screenshot 2023-11-11 at 11 46 57 AM](https://github.com/lancedb/lance/assets/5488879/9249cf9b-0a1b-4ccd-8dab-5fe45089a186)

On Linux, it's also generally good though there are some regressions for scans, which might be worth looking into:


![Screenshot 2023-11-11 at 11 59 52 AM](https://github.com/lancedb/lance/assets/5488879/a563d521-8d5c-4db5-a28d-1a68c78090da)

https://docs.google.com/spreadsheets/d/1hfPkVX0bkZTcWm1jSBdxWYl5zo24F2YfPqh98NYYY0w/edit#gid=1933822679

Overall, I'm inclined to wait until we understand why the regressions on Linux scans occurs.
