### ISSUE TITLE
bug: unable to parse GCP SA key in GHA

### ISSUE THREAD

**Issue by chebbyChefNEQ** [lancedb/lance#3647]
```
E       RuntimeError: lance error: LanceError(IO): Generic GCS error: Unable to decode service account file: unknown variant `external_account`, expected `service_account` or `authorized_user` at line 1 column 26, /root/.cargo/git/checkouts/lance-b31243ab5673a03e/33634d3/rust/lance-io/src/object_store.rs:967:25
```

I believe we can repro by
```yaml
- name: Set up Cloud SDK
  uses: 'google-github-actions/setup-gcloud@v2'
- uses: 'google-github-actions/auth@v2'
  with:
    project_id: ...
    workload_identity_provider: ...
    service_account: ...
```
